Домашнее задание 3
argraur/yandex-school-todo-android pull request #4
Opened 2024-07-06 03:01 UTC by argraur

Сделал сеть (Ktor(fit)) и базу данных (Room), подправил архитектуру.
Не сделал: Worker (чтобы в фоне каждые 8 часов синхронизировало, не завелось) и штука типа произвольная синхронизация по броадкасту о возвращении подключения к интернету, не успел, делал вот этой ночью как раз)

Если будут вопросы пиши пожалуйста сюда -> t.me/argraur

Прикрепляю APK, запакованный в зип, чтобы не пришлось собирать, там стоит мой токен, если захочешь сам(а) собрать внезапно, надо будет понизить версию AGP в libs.versions.toml до стабильной и прописать токен в local.properties:

```
token="<token>"
```

[app-release.zip](https://github.com/user-attachments/files/16114730/app-release.zip)

2024-07-07 19:11 UTC, nai1ka reviewed
Сеть (2/3)
✅ Добавил авторизационный токен
✅ Список получается с сервера
✅ Можно добавлять/удалять/изменять дела на сервере
✅ Есть обработка ошибок
⚠️ Могут быть неконсистентные данные на сервере и в локальной бд. Подробнее описал в комментариях к коду
❌ Нет автоматической загрузки данных при появлении интернете
❌ Нет обновления данных в фоне


Хранение данных (2/3)
✅ Приложение работает без интернета
❌ Синхронизация не работает
❌ Обновления данных в фоне не работает


Архитектура (3/3)
✅ Правильное разделение на слои
✅ Использованы Flow
✅ Минимум кода в активити
✅ Single Reponsibility выполняется, только забыл docstring
✅ Нет классов больше 300 строк

@nai1ka

2024-07-07 19:11 UTC, nai1ka commented on data/src/main/java/dev/argraur/yandex/todo/data/network/dto/NetworkTodoItem.kt
> +        lastUpdatedBy = "meow"
Забавно, не забудь поменять на идентификатор устройства)

2024-07-07 19:11 UTC, nai1ka commented on data/src/main/java/dev/argraur/yandex/todo/data/network/dto/NetworkTodoItem.kt
> +        importance = when(urgency) {
Странное решение, можно было в параметры enum класса поместить строку

2024-07-07 19:11 UTC, nai1ka commented on data/src/main/java/dev/argraur/yandex/todo/data/repository/TodoItemsRepositoryImpl.kt
> +        remoteDataSource.addTodoItem(item)
Если при добавлении дела интернет будет недоступен, то на сервере и на локалке будут разные данные. Как вариант, можешь синхронизировать при появлении интернета. Или просто не добавлять в локалку, если была ошибка сети

2024-07-07 19:32 UTC, argraur commented on data/src/main/java/dev/argraur/yandex/todo/data/repository/TodoItemsRepositoryImpl.kt
> +        remoteDataSource.addTodoItem(item)
Да, я хотел сделать сравнение данных по changedAt + ревизии для нормальной синхронизации, но не успел.

2024-07-07 19:32 UTC, argraur commented
@nai1ka Спасибо за проверку!!

2024-07-08 02:49 UTC, Zakis0 requested changes

2024-07-08 02:49 UTC, Zakis0 commented on data/src/main/java/dev/argraur/yandex/todo/data/workers/RefreshDataWorker.kt
> +// не работает, womp womp
Хорошее видео про WorkManager и Hilt. Делал по нему и всё заработало
https://www.youtube.com/watch?v=O9_RSYSmeIE&t

(Если будешь смотреть, то, как минимум, в версии моего Hilt нужно было делать вот так
override val workManagerConfiguration: Configuration
        
А не
override fun getWorkManagerConfiguration(): Configuration
)

2024-07-08 02:49 UTC, Zakis0 commented on ui/src/main/java/dev/argraur/yandex/todo/ui/screens/HomeScreen.kt
> +                colors = TopAppBarDefaults.largeTopAppBarColors(scrolledContainerColor = MaterialTheme.colorScheme.background),
Лучше не делать слишком длинные строки кода, т.к. код не удобно читать (Если что в чате договаривались считать многострочные конструкторы и т.д. как одну строку)

2024-07-08 02:49 UTC, Zakis0 commented
Если не повторять предыдущего проверяющего:
(В pull request не попало, так что пишу тут)
- Preview функции в compose лучше делать private
- Не уверен, что стоит эмоджи для текста писать в strings.xml

С замечаниями nai1ka согласен, так что оценка аналогичная

Работа понравилась. Особенно стиль кода.

2024-07-10 18:34 UTC, merged